version: '3.9
'

services:
  traefik: #prueba
    image: traefik:v2.10.1
    command: --api.insecure=true --providers.docker
    depends_on:
      - web
    networks:
      - traefik-net
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  web:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    networks:
      - traefik-net
    labels:
      - "traefik.http.routers.web.rule=Host(`saludvirtual.local.ve`) || PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
    container_name: saludvirtual-web
    #    volumes:
    #      - .:/saludvirtual
    depends_on:
      - database
    ports:
      - "8085:8085"
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    build:
      context: .
      dockerfile: ./docker/db.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: t00r
      MYSQL_USER: admin
      MYSQL_PASSWORD: 4dm1n
      MYSQL_DATABASE: saludvirtual
    container_name: saludvirtual-db
    ports:
      - 33066:3306
    volumes:
      - saludvirtual_data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    depends_on:
      - database
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: saludvirtual-pma


networks:
  traefik-net:
    external: true

volumes:
  saludvirtual_data: