FROM golang:1.20.5-bullseye as builder
ENV GO111MODULE=on
# Install git

RUN apt-get update && apt-get install -y --no-install-recommends git

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

# Copy the source from the current directory to the working Directory inside the container
COPY . .

# Run tests
CMD CGO_ENABLED=0 go test -v  ./...