version: '3'
services:


  app:
    container_name: goapirest_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - goapirest-mysql
      - phpmyadmin

    networks:
      - goapirest


  goapirest-mysql:
    image: mysql:8.0.33
    container_name: goapirest_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - goapirest

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - goapirest-mysql
    environment:
      - PMA_HOST=goapirest-mysql # Note the "goapirest-mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - goapirest


volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  goapirest:
    driver: bridge
